### ISSUE TITLE
"Cannot read property 'toLowerCase'" error when using multi remote `capabilities` configuration

### ISSUE THREAD

**Issue by marcrohloff** [webdriverio-community/wdio-chromedriver-service#36]
I was using Wdio 5.x and upgraded to 6.1 (the wdio-chromedriver-service is at version 6.0.3) which caused my tests to no longer run

I have multi remote configured according to these instructions https://webdriver.io/docs/multiremote.html#using-wdio-testrunner:
```
export.config = {
       // snip
        capabilities:  {
            browser1: { capabilities: { browserName: 'chrome'} },
            browser2: { capabilities: { browserName: 'chrome'} }
        },
       // snip
        services: [
            ['chromedriver', {
                args: ['--silent'] //
            } ]
        ],
       // snip
  }
```

 but when I run wdio I get the following in my console:
```
[0-0] RUNNING in MultiRemote - /test/specs/end_to_end_call.js
[0-0]  Error:  Failed to create session.
Unable to connect to "http://127.0.0.1:9222/", make sure browser driver is running on that address.
If you use services like chromedriver see initialiseServices logs above or in wdio.log file as the service might had problems to start the driver.
```
and the log file is as follows:
```
2020-05-28T23:49:10.964Z INFO @wdio/cli:launcher: Run onPrepare hook
2020-05-28T23:49:10.966Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
TypeError: Cannot read property 'toLowerCase' of undefined
    at isChrome (/home/marc/Projects/braidio/src/kandy_rtc_tester/node_modules/wdio-chromedriver-service/build/launcher.js:26:41)
    at ChromeDriverLauncher._mapCapabilities (/home/marc/Projects/braidio/src/kandy_rtc_tester/node_modules/wdio-chromedriver-service/build/launcher.js:87:13)
    at ChromeDriverLauncher.onPrepare (/home/marc/Projects/braidio/src/kandy_rtc_tester/node_modules/wdio-chromedriver-service/build/launcher.js:58:10)
    at /home/marc/Projects/braidio/src/kandy_rtc_tester/node_modules/@wdio/cli/build/utils.js:51:33
    at Array.map (<anonymous>)
    at runServiceHook (/home/marc/Projects/braidio/src/kandy_rtc_tester/node_modules/@wdio/cli/build/utils.js:49:39)
    at Launcher.run (/home/marc/Projects/braidio/src/kandy_rtc_tester/node_modules/@wdio/cli/build/launcher.js:79:40)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Is there something I am missing here?

**Comment by christian-bromann** [comment]
@marcrohloff I can't seem to reproduce this anymore using the latest version. Please let me know if you encounter any other issues. Thanks!
