### ISSUE TITLE
RequestError: connect ECONNREFUSED (Only one usage of each socket address is normally permitted)

### ISSUE THREAD

**Issue by vignesh-grexit** [webdriverio-community/wdio-chromedriver-service#66]
Issue: On running two specs simultaneously in different terminals, facing `RequestError: connect ECONNREFUSED`

here's the `wdio.conf.js` file used, 
```
exports.config = {
    specs: [
        './test/specs/test_one.js',
        './test/specs/test_two.js',
    ],
    maxInstances: 10,
    capabilities: [{
        maxInstances: 5,
        browserName: 'chrome',
        acceptInsecureCerts: true
    }],
    logLevel: 'debug',
    baseUrl: 'http://localhost',
    waitforTimeout: 10000,
    waitforInterval: 500,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    services: [
        ['chromedriver', {
            port: 7676
        }],
    ],
    framework: 'mocha',
    reporters: ['spec'],
    mochaOpts: {
        ui: 'bdd',
        bail: 1,
        timeout: 600000
    },
    // onPrepare: function (config, capabilities) {
    // },
    // onWorkerStart: function (cid, caps, specs, args, execArgv) {
    // },
    // onComplete: function(exitCode, config, capabilities, results) {
    // },
    // onReload: function(oldSessionId, newSessionId) {
    // }
}
```
here, I am running two specs `wdio wdio.conf.js --spec test_one.js` in **_terminal one_** and` wdio wdio.conf.js --spec test_two.js` in **_terminal two_** simultaneously 

On debugging I found that port 7676 is not available for **_terminal two_** because of the error `Only one usage of each socket address (protocol/network address/port) is normally permitted.`

logs
```
2021-12-24T09:58:32.943Z WARN chromedriver: [1640339912.943][SEVERE]: bind() returned an error: Only one usage of each socket address (protocol/network address/port) is normally permitted. (0x2740)
2021-12-24T09:58:32.944Z INFO chromedriver: IPv6 port not available. Exiting...



[0-0] 2021-12-24T09:58:35.926Z ERROR webdriver: RequestError: connect ECONNREFUSED 127.0.0.1:7676
[0-0]     at ClientRequest.<anonymous> (C:\Hiver\Workspace\qa-wdio\node_modules\got\dist\source\core\index.js:956:111)
[0-0]     at Object.onceWrapper (events.js:422:26)
[0-0]     at ClientRequest.emit (events.js:327:22)
[0-0]     at ClientRequest.EventEmitter.emit (domain.js:467:12)
[0-0]     at ClientRequest.origin.emit (C:\Hiver\Workspace\qa-wdio\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
[0-0]     at Socket.socketErrorListener (_http_client.js:469:9)
[0-0]     at Socket.emit (events.js:315:20)
[0-0]     at Socket.EventEmitter.emit (domain.js:467:12)
[0-0]     at emitErrorNT (internal/streams/destroy.js:106:8)
[0-0]     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
[0-0]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[0-0] FAILED in chrome - C:\Hiver\Workspace\qa-wdio\test\specs\hiver.tags.js
```

Is there any way to handle this?

Expected Solution : 
It would be better if ports are allocated dynamically if the specified port 7676 or default 9515 is already being used.
for example, in launcher.js `onPrepare()` I tried checking the port availability and assigning port dynamically as below which worked fine and the error was cleared.
```
        if (await tcpPortUsed.check(this.options.port, this.options.hostname)) {
            const server = net.createServer()
            const { port } = server.unref().listen().address()
            server.close()
            this.options.port = port;
        }
```

**Comment by christian-bromann** [comment]
@vignesh-grexit thanks for filing the issue.

I recommend here to pass in a second parameter on your second `wdio` call to tell the config not to add Chromedriver to the service list.

Let me know if you have further questions.

**Comment by vignesh-grexit** [comment]
@christian-bromann Thank you for recommending.

On trying out the approach I'm facing,
```
1. If I run the second wdio call without adding ChromeDriver in the service list, 
(i) port specified for automation protocol: if the execution at first wdio call ends before second wdio call, again it results in the same error
(ii) port not specified for automation protocol: it starts in devTools protocol, which is not the target here
the reason why devTools protocol is not preferred here : 
     a. I will be using the extension, and facing issues on loading extension (windows handles)
     b. maximizing the window is not possible (browser.maximizeWindow() or --start-maximized both not working)

2. I will be running 5-7 specs simultaneously and the order of execution will be random based on Jenkins and failure retries.
```

Is there any other approach to handle this?
